name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configuração do Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Executar script para gerar a animação
        run: |
          python3 generate_github_snake.py
          mv github-snake.svg saída/github-snake.svg

      - name: Fazer upload do arquivo gerado
        uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: saída/github-snake.svg
